FROM golang:1.19

RUN  mkdir /opt/buf && cd /opt/buf && wget "https://github.com/bufbuild/buf/releases/download/v1.14.0/buf-$(uname -s)-$(uname -m).tar.gz" && \
     tar -xvzf buf-$(uname -s)-$(uname -m).tar.gz --strip-components 1

ENV PATH="$PATH:$(go env GOPATH)/bin"

WORKDIR /app

COPY proto ./proto
COPY server ./server
COPY *.yaml ./
COPY go.mod ./
COPY go.sum ./
RUN /opt/buf/bin/buf generate
RUN go mod download
RUN go build -o bin/server ./server

CMD [ "/app/bin/server" ]